### ISSUE TITLE
根据游戏类型设置时间

### ISSUE THREAD

**Issue by Cologler** [TankNee/LOL_Game_Subscription#11]
现在所有比赛都是 2 小时。

看了一下 `https://lpl.qq.com/web201612/data/LOL_MATCH2_MATCH_HOMEPAGE_BMATCH_LIST.js`，发现 `GameMode` 字段只有 3 种类型：

z|`GameMode`|`GameModeName`|实际时长
:-:|:-:|:-:|:-:
z|`"1"`|`"BO1"`|1
z|`"3"`|`"BO3"`|3
z|`"4"`|`"BO5"`|5

**Comment by TankNee** [comment]
感谢你提供的信息，游戏时长已经根据game mode来设置了，不过鉴于bo5很少打满5个小时，我将时间分别设置为1，3，4小时每局。
等cdn刷新即可。
![CleanShot 2024-03-07 at 21 22 00@2x](https://github.com/TankNee/LOL_Game_Subscription/assets/43956168/578fd233-d7a3-43b7-bb09-9b4df5a60e77)
