### ISSUE TITLE
[enhancement]请考虑添加对google calendar的支持

### ISSUE THREAD

**Issue by zzz6839** [TankNee/LOL_Game_Subscription#2]
![image](https://user-images.githubusercontent.com/57741549/148719132-7f6f06ef-9169-4ed7-be99-341ab2073b31.png)
url订阅会在google calender上出现格式错误导致时区问题，需要手动import文件，能修复下吗

**Comment by ChengLuffy** [comment]
时间格式错误，好像部分软件只支持UTC

参考：
https://www.kanzaki.com/docs/ical/dtstart.html
https://stackoverflow.com/questions/47274517/ical-dtstart-and-dtend-format-confusion-should-be-easy-to-answer

**Comment by TankNee** [comment]
我不知道你用的是iOS还是Android，我用的iOS。我将订阅URL导入自带的日历中之后再用Google Calendar打开是可以正常显示时间的，iOS的Google Calendar我没有找到可以导入订阅URL的地方。

**Comment by wynfred** [comment]
请问这个问题最后怎么解决的？google calendar网页版就可以导入。能改成用UTC吗

**Comment by zzz6839** [comment]
解决不了，直接开摆（已解决，用IOS 自带的calendar：）

**Comment by ChengLuffy** [comment]
@wynfred @zzz6839 我知道如何修复（抱歉因为需要先学一点点 javascript 所以一直拖着），已提交 Pull Request，不过由于我从没用过 google calendar 需要两位尝试一个测试文件，目前我自己在网页版 google calendar 测试正常，测试文件见 gist 

https://gist.githubusercontent.com/ChengLuffy/2e353b65206f1696bba6e8569f661e8a/raw/a7cd845e4f4de8cfa7a9cb60f8dc7d4f20dd4fe7/gistfile1.txt

**Comment by zzz6839** [comment]
> @wynfred @zzz6839 我知道如何修复（抱歉因为需要先学一点点 javascript 所以一直拖着），已提交 Pull Request，不过由于我从没用过 google calendar 需要两位尝试一个测试文件，目前我自己在网页版 google calendar 测试正常，测试文件见 gist
> 
> https://gist.githubusercontent.com/ChengLuffy/2e353b65206f1696bba6e8569f661e8a/raw/a7cd845e4f4de8cfa7a9cb60f8dc7d4f20dd4fe7/gistfile1.txt

感谢修复，我这边网页版IOS版本都没有问题。

**Comment by ChengLuffy** [comment]
> > @wynfred @zzz6839 我知道如何修复（抱歉因为需要先学一点点 javascript 所以一直拖着），已提交 Pull Request，不过由于我从没用过 google calendar 需要两位尝试一个测试文件，目前我自己在网页版 google calendar 测试正常，测试文件见 gist
> > https://gist.githubusercontent.com/ChengLuffy/2e353b65206f1696bba6e8569f661e8a/raw/a7cd845e4f4de8cfa7a9cb60f8dc7d4f20dd4fe7/gistfile1.txt
> 
> 感谢修复，我这边网页版IOS版本都没有问题。

OK 删除那个日历等仓库作者合并或修复吧，gist 后续不会更新

**Comment by TankNee** [comment]
奇怪，这个问题在Google Calendar中使用链接订阅的时候会有，但是如果直接将ics文件导入就没啥问题....

**Comment by TankNee** [comment]
> 需要手动import文件

sorry，没看到你描述了这个。我觉得是Google后台处理有问题，你自己的日历可以设置时区，但是订阅的日历不能设置时区，导入文件是直接用的你自己设定的时区？而订阅的就直接按照Google本地的来？我猜的

**Comment by TankNee** [comment]
问题已经解决了，cdn可能需要一段时间才能把缓存更新过来，过段时间应该就能用了。

**Comment by TankNee** [comment]
主要是GitHub Action的服务器和我本地时区不一致把我绕晕了。
