### ISSUE TITLE
2023LPL队伍名称后面有空格

### ISSUE THREAD

**Issue by Daniel011011** [TankNee/LOL_Game_Subscription#6]
例如
SUMMARY:FPX	vs WE - 1 : 2

FPX，BLG，TES等都有

**Comment by TankNee** [comment]
什么叫有空格？在summary这个字段，名字后面就是有空格的。

**Comment by Daniel011011** [comment]
今天的三场比赛
SUMMARY:LGD	vs RA
SUMMARY:OMG vs RNG
SUMMARY:NIP vs UP

只有LGD后面有额外的空格，FPX，BLG。[
![Snipaste_2023-01-15_22-34-58](https://user-images.githubusercontent.com/89135196/212546966-97468036-49f9-4f7b-9663-aa55c2e48d7d.png)
](url)

**Comment by Daniel011011** [comment]
![IMG_1886](https://user-images.githubusercontent.com/89135196/212547033-c85867c3-b6a5-4c14-8b7c-f7e1d5f6593b.PNG)
ru't如图

**Comment by TankNee** [comment]
了解了

**Comment by TankNee** [comment]
你好，今天我又看了一下，似乎没有这个问题了？

**Comment by TankNee** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/43956168/216761581-9860d0ae-5b81-4c8e-bce4-42b0407d4f58.png">

**Comment by Daniel011011** [comment]
![BD68EC9C-E814-4843-B07C-E5C55B9DB880](https://user-images.githubusercontent.com/89135196/216766531-63496004-16a5-4a22-ac08-b383566f7ed0.png)
紫色的是你的订阅链接，绿色是其他人的。在手机日历里面好像就看得见空格。5号tes那场
![59689237-D91F-4192-9EC0-AFF57F1B84CA](https://user-images.githubusercontent.com/89135196/216766614-9286945e-4b5b-44da-8535-1157dd90e29b.jpeg)
ipad上就看不见。

**Comment by Daniel011011** [comment]
![3C8E3148-F7D3-41BA-8DB2-4D7537759E5C](https://user-images.githubusercontent.com/89135196/216766851-6d21eb44-e2d5-41fe-b3d7-cbf1022a6b78.jpeg)
![2F1E8766-1B28-4982-B233-0ED375CEB550](https://user-images.githubusercontent.com/89135196/216766855-fd6ee6a1-21fb-4907-85e2-309a1135de10.jpeg)
如果点开ipad端的具体日程，详情里面也能看到TES后面多了空格。

可能是什么其他格式的空格，会在某些地方某些字体下被忽略成一个空格？

**Comment by Daniel011011** [comment]
![37F6E8C5-8AFD-47ED-8B1F-117DA986BF8E](https://user-images.githubusercontent.com/89135196/216767021-f6c06938-9e5f-4874-8716-4cb426dfa379.jpeg)

直接手机浏览器打开code也能看见这个空格，第一条nip vs jdg就没有。

![DB2873E7-F726-49C6-A4A4-FAA8C09D660F](https://user-images.githubusercontent.com/89135196/216767113-02b1f9f9-db0c-4614-902a-3e341cda8904.png)

手机端日历里也是对应队伍后有空格。

**Comment by TankNee** [comment]
点开才能看到，我这边也有，我排查一下

**Comment by TankNee** [comment]
已经修复了，应该是赛程API给的文本有问题，等cdn缓存刷新应该就能恢复正常。
